# Generated by Django 4.1.5 on 2023-01-26 09:26

from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ("deliverers", "0001_initial"),
        ("menus", "0001_initial"),
        ("customers", "0002_cart"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "_id",
                    djongo.models.fields.ObjectIdField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("order_time", models.DateTimeField(auto_now_add=True)),
                ("delivery_time", models.DateTimeField(auto_now_add=True, null=True)),
                ("delivered", models.BooleanField(default=False)),
                ("total_cost", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="customers.customer",
                    ),
                ),
                (
                    "deliverer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="deliverers.deliverer",
                    ),
                ),
                ("menus", models.ManyToManyField(to="menus.menu")),
            ],
        ),
    ]
