# Generated by Django 4.1.5 on 2023-01-23 11:27

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Deliverer",
            fields=[
                (
                    "_id",
                    djongo.models.fields.ObjectIdField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("last_name", models.CharField(max_length=255)),
                ("first_name", models.CharField(max_length=255)),
                ("status", models.CharField(default="free", max_length=255)),
                ("position", models.CharField(max_length=255)),
                ("command_count", models.IntegerField()),
                ("rating", models.FloatField()),
            ],
        ),
    ]
